export interface Country {
	name: string;
}

export const COUNTRIES: Country[] = [
	{'name': 'Afghanistan'},
	{'name': 'Albania'},
	{'name': 'Algeria'},
	{'name': 'American Samoa'},
	{'name': 'Andorra'},
	{'name': 'Angola'},
	{'name': 'Antarctica'},
	{'name': 'Antigua and Barbuda'},
	{'name': 'Argentina'},
	{'name': 'Armenia'},
	{'name': 'Australia'},
	{'name': 'Austria'},
	{'name': 'Azerbaijan'},
	{'name': 'Bahamas'},
	{'name': 'Bangladesh'},
	{'name': 'Barbados'},
	{'name': 'Belarus'},
	{'name': 'Belgium'},
	{'name': 'Belize'},
	{'name': 'Bermuda'},
	{'name': 'Bhutan'},
	{'name': 'Bolivia'},
	{'name': 'Bosnia and Herzegovina'},
	{'name': 'Botswana'},
	{'name': 'Brazil'},
	{'name': 'British Indian Ocean Territory'},
	{'name': 'Brunei Darussalam'},
	{'name': 'Bulgaria'},
	{'name': 'Burkina Faso'},
	{'name': 'Burundi'},
	{'name': 'Cambodia'},
	{'name': 'Cameroon'},
	{'name': 'Canada'},
	{'name': 'Cape Verde'},
	{'name': 'Cayman Islands'},
	{'name': 'Central African Republic'},
	{'name': 'Chad'},
	{'name': 'Chile'},
	{'name': 'China'},
	{'name': 'Christmas Island'},
	{'name': 'Cocos (Keeling) Islands'},
	{'name': 'Colombia'},
	{'name': 'Congo'},
	{'name': 'Congo, the Democratic Republic of the'},
	{'name': 'Cook Islands'},
	{'name': 'Costa Rica'},
	{'name': "Cote D'Ivoire"},
	{'name': 'Croatia'},
	{'name': 'Cuba'},
	{'name': 'Cyprus'},
	{'name': 'Czech Republic'},
	{'name': 'Denmark'},
	{'name': 'Djibouti'},
	{'name': 'Dominican Republic'},
	{'name': 'Ecuador'},
	{'name': 'Egypt'},
	{'name': 'El Salvador'},
	{'name': 'Eritrea'},
	{'name': 'Estonia'},
	{'name': 'Faroe Islands'},
	{'name': 'Fiji'},
	{'name': 'Finland'},
	{'name': 'France'},
	{'name': 'French Polynesia'},
	{'name': 'French Southern Territories'},
	{'name': 'Gambia'},
	{'name': 'Georgia'},
	{'name': 'Germany'},
	{'name': 'Ghana'},
	{'name': 'Gibraltar'},
	{'name': 'Greece'},
	{'name': 'Greenland'},
	{'name': 'Guadeloupe'},
	{'name': 'Guam'},
	{'name': 'Guatemala'},
	{'name': 'Guinea-Bissau'},
	{'name': 'Heard Island and Mcdonald Islands'},
	{'name': 'Holy See (Vatican City State)'},
	{'name': 'Honduras'},
	{'name': 'Hong Kong'},
	{'name': 'Hungary'},
	{'name': 'Iceland'},
	{'name': 'India'},
	{'name': 'Indonesia'},
	{'name': 'Iran, Islamic Republic of'},
	{'name': 'Iraq'},
	{'name': 'Ireland'},
	{'name': 'Israel'},
	{'name': 'Italy'},
	{'name': 'Jamaica'},
	{'name': 'Japan'},
	{'name': 'Jordan'},
	{'name': 'Kazakhstan'},
	{'name': 'Kenya'},
	{'name': "Korea, Democratic People's Republic of"},
	{'name': 'Korea, Republic of'},
	{'name': 'Kuwait'},
	{'name': "Lao People's Democratic Republic"},
	{'name': 'Latvia'},
	{'name': 'Lebanon'},
	{'name': 'Libyan Arab Jamahiriya'},
	{'name': 'Liechtenstein'},
	{'name': 'Lithuania'},
	{'name': 'Luxembourg'},
	{'name': 'Macedonia'},
	{'name': 'Malaysia'},
	{'name': 'Maldives'},
	{'name': 'Malta'},
	{'name': 'Martinique'},
	{'name': 'Mauritius'},
	{'name': 'Mexico'},
	{'name': 'Micronesia, Federated States of'},
	{'name': 'Moldova'},
	{'name': 'Mongolia'},
	{'name': 'Montenegro'},
	{'name': 'Montserrat'},
	{'name': 'Morocco'},
	{'name': 'Mozambique'},
	{'name': 'Nauru'},
	{'name': 'Nepal'},
	{'name': 'Netherlands'},
	{'name': 'Netherlands Antilles'},
	{'name': 'New Caledonia'},
	{'name': 'New Zealand'},
	{'name': 'Nicaragua'},
	{'name': 'Nigeria'},
	{'name': 'Niue'},
	{'name': 'Norfolk Island'},
	{'name': 'Northern Mariana Islands'},
	{'name': 'Norway'},
	{'name': 'Oman'},
	{'name': 'Pakistan'},
	{'name': 'Palestinian Territory, Occupied'},
	{'name': 'Panama'},
	{'name': 'Paraguay'},
	{'name': 'Peru'},
	{'name': 'Philippines'},
	{'name': 'Pitcairn'},
	{'name': 'Poland'},
	{'name': 'Portugal'},
	{'name': 'Puerto Rico'},
	{'name': 'Qatar'},
	{'name': 'Reunion'},
	{'name': 'Romania'},
	{'name': 'Russian Federation'},
	{'name': 'Saint Pierre and Miquelon'},
	{'name': 'Saint Vincent and the Grenadines'},
	{'name': 'Samoa'},
	{'name': 'San Marino'},
	{'name': 'Saudi Arabia'},
	{'name': 'Serbia'},
	{'name': 'Seychelles'},
	{'name': 'Singapore'},
	{'name': 'Slovakia'},
	{'name': 'Slovenia'},
	{'name': 'Somalia'},
	{'name': 'South Africa'},
	{'name': 'South Georgia and the South Sandwich Islands'},
	{'name': 'Spain'},
	{'name': 'Sri Lanka'},
	{'name': 'Sudan'},
	{'name': 'Sweden'},
	{'name': 'Switzerland'},
	{'name': 'Syrian Arab Republic'},
	{'name': 'Taiwan'},
	{'name': 'Tajikistan'},
	{'name': 'Tanzania, United Republic of'},
	{'name': 'Thailand'},
	{'name': 'Trinidad and Tobago'},
	{'name': 'Tunisia'},
	{'name': 'Turkey'},
	{'name': 'Turkmenistan'},
	{'name': 'Turks and Caicos Islands'},
	{'name': 'Tuvalu'},
	{'name': 'Uganda'},
	{'name': 'Ukraine'},
	{'name': 'United Arab Emirates'},
	{'name': 'United Kingdom'},
	{'name': 'United States'},
	{'name': 'United States Minor Outlying Islands'},
	{'name': 'Uruguay'},
	{'name': 'Uzbekistan'},
	{'name': 'Vanuatu'},
	{'name': 'Venezuela'},
	{'name': 'Viet Nam'},
	{'name': 'Virgin Islands, British'},
	{'name': 'Virgin Islands, U.s.'},
	{'name': 'Wallis and Futuna'},
	{'name': 'Western Sahara'},
	{'name': 'Yemen'},
	{'name': 'Zimbabwe'}
];
